In [1]:
import os
import pandas as pd

In [2]:
pwd

'/home/sarth/anaconda3/company_task/SampleInputDirectory'

In [11]:
paths = []
for root, dirs, files in os.walk('/home/sarth/anaconda3/company_task/SampleInputDirectory'):
    for file in files:
        # print(file)
        if file.endswith(".csv"):
            #print(file)
            s = os.path.join(root, file)
            paths.append(s)
all_data = pd.DataFrame()
for file in paths:
    #print(file)
    df = pd.read_csv(file)
    df["Symbol"]=file.split("/")[-1].split(" ")[0]
    df["ExpireDate"]=file.split("/")[-1].split("  ")[0][5:14]
    df["OptionType"]= file.split("/")[-1].split(" ")[-2]
    df["StrikePrice"]=file.split("/")[-1].split(" ")[-1].split(".")[0]
    #print(df)
    all_data = all_data.append(df, ignore_index=True)
    a = all_data.iloc[0:6]
    b = all_data.iloc[6:17]
a.to_csv('master_table.csv', index=False)
b.to_csv('second_master_table.csv', index=False)

In [12]:
a

,Timestamp,Last,LastSize,TotalVolume,Bid,Ask,TickId,BasisForLast,TradeMarketCenter,TradeConditions,Symbol,ExpireDate,OptionType,StrikePrice
0,13:37:27.483,0.54,1,1.0,0.10,1.00,3058525,C,13,45.0,ABC,1 NOV 19,CALL,86
1,14:37:27.483,0.54,1,2.0,0.10,1.00,3058525,O,13,45.0,ABC,1 NOV 19,CALL,86
2,15:37:27.483,0.80,29,31.0,0.40,0.85,77148452,C,17,27.0,ABC,1 NOV 19,CALL,86
3,12:13:06.366,1.72,1,1.0,1.66,1.76,41913977,C,13,45.0,ABBV,29 NOV 19,PUT,81
4,13:13:06.366,1.55,2,3.0,1.55,1.59,62384783,C,156,1.0,ABBV,29 NOV 19,PUT,81
5,14:13:06.366,1.55,2,5.0,1.50,1.55,63161255,C,17,20.0,ABBV,29 NOV 19,PUT,81

In [13]:
#symbol,expiredate,optiontype,strikeprice
file.split("/")[-1].split(" ")[-2]

'PUT'

In [141]:
a = all_data.iloc[0:7]

In [148]:
a

,Timestamp,Last,LastSize,TotalVolume,Bid,Ask,TickId,BasisForLast,TradeMarketCenter,TradeConditions,Symbol,ExpireDate,OptionType,StrikePrice
0,13:37:27.483,0.54,1,1.0,0.10,1.00,3058525,C,13,45.0,ABC,1 NOV 19,CALL,86
1,14:37:27.483,0.54,1,2.0,0.10,1.00,3058525,O,13,45.0,ABC,1 NOV 19,CALL,86
2,15:37:27.483,0.80,29,31.0,0.40,0.85,77148452,C,17,27.0,ABC,1 NOV 19,CALL,86
3,12:13:06.366,1.72,1,1.0,1.66,1.76,41913977,C,13,45.0,ABBV,29 NOV 19,PUT,81
4,13:13:06.366,1.55,2,3.0,1.55,1.59,62384783,C,156,1.0,ABBV,29 NOV 19,PUT,81
5,14:13:06.366,1.55,2,5.0,1.50,1.55,63161255,C,17,20.0,ABBV,29 NOV 19,PUT,81